# Generated by Django 4.0.5 on 2022-06-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_followerscount_likepost_remove_follow_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerscount',
            name='follower',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
